version: "3.8"
services:
  backend:
    command: >
      sh -c
      "python manage.py collectstatic --noinput && 
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    build: ./backend
    stdin_open: true
    tty: true
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

volumes:
  node_modules: