# Generated by Django 3.2.18 on 2023-03-16 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_auto_20230312_2152"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="updated_date",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="updated_date",
            new_name="updated_at",
        ),
    ]
