# Generated by Django 3.2.18 on 2023-04-30 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_pollanswer_pollcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pollanswer",
            name="author",
        ),
    ]
