# Generated by Django 3.2.18 on 2023-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_remove_pollanswer_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="votes",
        ),
        migrations.AddField(
            model_name="pollanswer",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
