# Generated by Django 3.2.18 on 2023-05-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0007_alter_poll_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollcomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_comments",
                to="polls.pollcomment",
            ),
        ),
    ]
