# Generated by Django 3.2.18 on 2023-05-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog_posts", "0004_userlikedblogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostcomment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nested_comments",
                to="blog_posts.blogpostcomment",
            ),
        ),
    ]
