# Generated by Django 3.2.18 on 2023-04-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_category_options"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favourite_categories",
            field=models.ManyToManyField(
                related_name="_users_user_favourite_categories_+", to="common.Category"
            ),
        ),
    ]
